plugins:
  required:
    github: latest
    git: latest
    matrix-auth: latest
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 3
  securityRealm:
    local:
      allowsSignup: true
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Administer:admin"
        - "Overall/Read:NMadaan"
tool:
  git:
    installations:
      - name: Default
        home: git
      - name: New
        home: /usr/bin/git
jobs:
  - script: >
      pipelineJob('Jenkins-Casc') {
          definition {
              configure { it / 'triggers' / 'com.cloudbees.jenkins.GitHubPushTrigger' / 'spec' }
              cpsScm {
                  scriptPath 'Jenkins-Casc_Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/nmadaan/jcasc/' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }
