plugins:
  required:
    github: latest
    git: latest
    matrix-auth: latest
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  securityRealm:
    local:
      allowsSignup: true
tool:
  git:
    installations:
      - name: Default
        home: git
jobs:
  - script: >
      pipelineJob('Jenkins-Springboot-Demo') {
          definition {
              configure { it / 'triggers' / 'com.cloudbees.jenkins.GitHubPushTrigger' / 'spec' }
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/nmadaan/jenkins-demo-springboot.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }
      queue('Jenkins-Springboot-Demo')
